# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project/My-Chickenbreast-Shop
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu