#spring:
#  profiles:
#    group:
#      local-dev : dev, service
#    active: local-dev

spring :
  profiles:
    active: real-dev

# logging
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
