#spring:
#  profiles:
#    group:
#      local-dev : dev, service
#    active: local-dev

spring:
  profiles:
    active: release

# logging
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com:
      amazonaws:
        util:
          EC@MetadataUtils: error
