# deploy.yml

name: test-deploy

on: 
  push:
    branches: master
    
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Set up JDK 17
       uses: actions/set-up@v3
       with:
        java-version: "17"

     - name: Grand execute permission for gradlew
       run: chmod +x gradlew

     - name: Build with Gradle
       run: ./gradlew bootJar
