# deploy.yml

name: test-deploy

on: 
  push:
    branches: master

env:
  S3_BUCKET_NAME: my-test-first-s3-bucket
  PROJECT_NAME: My-Chickenbreast-Shop

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Set up JDK 17
       uses: actions/setup-java@v2
       with:
        java-version: 17
        distribution: zulu

     - name: Grand execute permission for gradlew
       run: chmod +x gradlew

     - name: Build with Gradle
       run: ./gradlew bootJar

     - name: Make jar to zip file
       run: zip -r ./$GITHUB_SHA.zip .

     - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}

     - name: Upload to S3
       run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
